my_test/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from test1.views import *

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^test1/', include('test1.urls', namespace='test1')),
]

test1/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^add_handle/$', views.add_handle, name='add_handle'),
]

test1/models.py
from db.BaseModel import *
from django.db import models


class CagManager(models.Manager):
    # 根据用户名查询用户
    def get_caginfo_by_name(self, cags_name):

        try:
            return self.get(cag_name=cags_name)
        except Category.DoesNotExist:
            return None


class Category(BaseModel):
    cag_name = models.CharField(max_length=30);
    cag_link = models.CharField(max_length=100);

    objects = CagManager()


class GoodsList(BaseModel):
    goods_name = models.CharField(max_length=30)
    goods_link = models.CharField(max_length=100)
    goods_cag = models.ForeignKey(Category)

# desc test1_category;
# +-------------+--------------+------+-----+---------+----------------+
# | Field       | Type         | Null | Key | Default | Extra          |
# +-------------+--------------+------+-----+---------+----------------+
# | id          | int(11)      | NO   | PRI | NULL    | auto_increment |
# | create_time | datetime(6)  | NO   |     | NULL    |                |
# | update_time | datetime(6)  | NO   |     | NULL    |                |
# | is_delete   | tinyint(1)   | NO   |     | NULL    |                |
# | cag_name    | varchar(30)  | NO   |     | NULL    |                |
# | cag_link    | varchar(100) | NO   |     | NULL    |                |
# +-------------+--------------+------+-----+---------+----------------+
#
#  desc test1_goodslist;
# +--------------+--------------+------+-----+---------+----------------+
# | Field        | Type         | Null | Key | Default | Extra          |
# +--------------+--------------+------+-----+---------+----------------+
# | id           | int(11)      | NO   | PRI | NULL    | auto_increment |
# | create_time  | datetime(6)  | NO   |     | NULL    |                |
# | update_time  | datetime(6)  | NO   |     | NULL    |                |
# | is_delete    | tinyint(1)   | NO   |     | NULL    |                |
# | goods_name   | varchar(30)  | NO   |     | NULL    |                |
# | goods_link   | varchar(100) | NO   |     | NULL    |                |
# | goods_cag_id | int(11)      | NO   | MUL | NULL    |                |
# +--------------+--------------+------+-----+---------+----------------+

test1/views.py
from django.shortcuts import render
from .models import *
from utils.wrappers import *
from django.http import HttpResponse


def index(request):
    cags = Category.objects.all()
    return render(request, 'test_page.html', locals())


def add_handle(request):
    # 先获取cag_name,去数据库查询是否存在
    cags_name = post(request, 'cag_name')
    good_name = post(request, 'goods_name')
    # 健壮性判断，减少服务器压力
    if cags_name == '' or good_name == '':
        return
    # cag_name默认不存在
    flag = False
    cag = Category.objects.get_caginfo_by_name(cags_name)
    if cag:
        flag = True

    # cag_name 存在，只新增商品信息
    if flag:
        goods = GoodsList()
        goods.goods_name = good_name
        goods.goods_link = good_name
        goods.goods_cag_id = cag.id
        goods.save()
        return HttpResponse('新增{}类商品成功!'.format(cags_name))
    else:
        cag = Category()
        goods = GoodsList()
        cag.cag_name = cags_name
        cag.cag_link = 'By ' + cags_name
        cag.save()
        goods.goods_name = good_name
        goods.goods_link = good_name
        goods.goods_cag_id = cag.id
        goods.save()
        return HttpResponse('新增类别商品成功！')

templates/test_page.html
{% load staticfiles %}
<html>
<head>
    <title>Home</title>
    <!-- Custom Theme files -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="keywords" content=""/>
    <script type="application/x-javascript"> addEventListener("load", function () {
        setTimeout(hideURLbar, 0);
    }, false);
    function hideURLbar() {
        window.scrollTo(0, 1);
    } </script>
    <!-- //Custom Theme files -->
    <link href="{% static 'css/bootstrap.css' %}" type="text/css" rel="stylesheet" media="all">
    <link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet" media="all">
    <!-- js -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap-3.1.1.min.js' %}"></script>
    <!-- //js -->
    <script src="{% static 'js/simpleCart.min.js' %}"></script>
    <!-- cart -->
</head>
<body>
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
        <li><a href="#">Home</a></li>
        {% for cag in cags %}

            <li class="dropdown">
                <a href="{{ cag.cag_link }}" class="dropdown-toggle" data-toggle="dropdown">{{ cag.cag_name }}<b
                        class="caret"></b></a>
                <ul class="dropdown-menu multi-column columns-4">
                    <div class="row">
                        <div class="col-sm-3">
                            <h4>By {{ cag.cag_name }}</h4>
                            <ul class="multi-column-dropdown">
                                {% for goods in cag.goodslist_set.all %}
                                    <li><a class="list" href="{{ goods.goods_link }}">{{ goods.goods_name }}</a></li>
                                {% endfor %}

                            </ul>
                        </div>

                    </div>
                </ul>
            </li>
        {% endfor %}


    </ul>
    <!--/.navbar-collapse-->
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="site_con">
    <form method="post" action="{% url 'test1:add_handle' %}">
        {% csrf_token %}
        <div class="form_group">
            <label>Add Category:</label>
            <input type="text" name="cag_name" placeholder="分类名，如果没有就会新建">
        </div>
        <div class="form_group form_group2">
            <label>Add Goods:</label>
            <textarea class="site_area" name="goods_name" placeholder="详细商品名"></textarea>
        </div>

        <input type="submit" name="" value="submit" class="info_submit">
    </form>
</div>
</body>
</html>